# render.yaml

services:
  - type: web
    name: text-embedding-service
    env: python
    plan: free
    
    # === Build Configuration ===
    buildCommand: "pip install -r requirements.txt"
    
    # === CORRECTED Start Command ===
    # We must tell uvicorn to run the 'app' object from the 'render_app' module (render_app.py)
    startCommand: "uvicorn render_app:app --host 0.0.0.0 --port $PORT"
    
    # === Persistent Disk for Caching ===
    # This creates a writable disk at the specified mount path.
    # Our app.py will write its cache inside this directory.
    disks:
      - name: hf-cache
        mountPath: /var/data/huggingface_cache # This path is now correct
        sizeGB: 2

    # === Health Check ===
    healthCheckPath: /