services:
  - type: web
    name: text-embedding-service # Or whatever you named your service
    env: python
    plan: free # This confirms we are targeting the free tier
    
    buildCommand: "pip install -r requirements.txt"
    
    # This start command is correct
    startCommand: "uvicorn render_app:app --host 0.0.0.0 --port $PORT"
    
    # REMOVED: The entire 'disks' section is deleted because it's not supported.
    
    healthCheckPath: /